[IO ports]
AC_Output1 = Dev1/ao1
AC_Output2 = Dev1/ao2
Coils_Output = Dev1/ao3
Balanced_diodes_Input = Dev1/ai0
Intensity_diode_Input = Dev1/ai1
# The id of lockin is set in the amteck7270_class.py